config/routes.rb
Rails.application.routes.draw do

  root "shops#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:edit,:update]
  resources :shops do
    resources :comments
  end
  delete "/shops/:id" => "shops#destroy", as: "destroy_shop"
  get "home/about" => "home#about"
  get "home/top" => "home#top"
  get "home/terms" => "home#terms"
  get "home/privacy" => "home#privacy"

end

app/models/shop.rb
# == Schema Information
#
# Table name: shops
#
#  id              :integer          not null, primary key
#  shop_name       :string
#  shop_image_id   :text
#  phonenum        :string
#  postalcode      :string
#  address         :text
#  description     :text
#  regular_holiday :string
#  access          :string
#  business_hours  :string
#  opening_date    :string
#  homepage        :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Shop < ApplicationRecord

    has_many :comments, dependent: :destroy
	has_many :genres, dependent: :destroy
	accepts_nested_attributes_for :genres, allow_destroy: true

	has_one_attached :shop_image

	validates :shop_name, presence: true
	validates :phonenum, presence: true, length: { in: 10..11 }
	validates :postalcode, presence: true, length: { is: 7 }
	validates :address, presence: true
	validates :description, presence: true
	validates :regular_holiday, presence: true
	validates :access, presence: true
	validates :business_hours, presence: true
	# validates :opening_date, presence: true

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

	  def index
      # genre関係なく全て取り出す
      @shops = Shop.page(params[:page]).reverse_order
      # genreが0(食料・飲料)に当てはまるもの
      @genre_food = Genre.where(genre: 0).page(params[:page]).reverse_order
      # genreが1(ファッション)に当てはまるもの
      @genre_fashion = Genre.where(genre: 1).page(params[:page]).reverse_order
      # genreが2(日用品)に当てはまるもの
      @genre_daily = Genre.where(genre: 2).page(params[:page]).reverse_order
      # genreが3(雑貨)に当てはまるもの
      @genre_general = Genre.where(genre: 3).page(params[:page]).reverse_order
      # genreが4(地産地消)に当てはまるもの
      @genre_local = Genre.where(genre: 4).page(params[:page]).reverse_order
      # genreが5(セレクトショップ)に当てはまるもの
      @genre_select = Genre.where(genre: 5).page(params[:page]).reverse_order
    end

  	def new
      @shop = Shop.new
      @genre = @shop.genres.build
  	end

  	def create
      @shop = Shop.new(shop_params)
      @shop.save
      redirect_to("/shops")
  	end

  	def show
      @shop = Shop.find(params[:id])
      @comment = Comment.new
  	end

  	def edit
      @shop = Shop.find(params[:id])
  	end

  	def update
      @shop = Shop.find(params[:id])
      if @shop.update(update_show_params)
        redirect_to("/shops")
      else
        render :edit
      end
  	end

  	def destroy
      @shop = Shop.find(params[:id])
      @shop.destroy
      redirect_to("/shops")
  	end

  private

    def shop_params
      params.require(:shop).permit(:shop_name,
                                   :shop_image,
                                   :phonenum,
                                   :postalcode,
                                   :address,
                                   :description,
                                   :regular_holiday,
                                   :access,
                                   :business_hours,
                                   :opening_date,
                                   :homepage,
                                    genres_attributes: [:genre]
                                  )
    end

    def update_show_params
      params.require(:shop).permit(:shop_name,
                                   :shop_image,
                                   :phonenum,
                                   :postalcode,
                                   :address,
                                   :description,
                                   :regular_holiday,
                                   :access,
                                   :business_hours,
                                   :opening_date,
                                   :homepage,
                                    genres_attributes: [:genre, :_destroy, :id]
                                  )
    end

end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/edit.html.erb
<div class="container">
  <div class="row">
	<div class="card shopedit-card" style="width: 25rem;">
	  <div class="card-body">
		<h5 class="card-title">お店の編集</h5>
		<hr class="my-3">

		<%= form_with model: @shop do |form| %>

		  <div class="field">
			<span class="form-label">店舗画像:</span><br />
	          <%= form.file_field :shop_image %>
	      </div>

	      <div class="field">
			<span class="form-label">店名</span><br />
	        <%= form.text_field :shop_name %>
	      </div>

	      <div class="field">
			<span class="form-label">電話番号</span><br />
	        <%= form.text_field :phonenum %>
	      </div>

	      <div class="field">
			<span class="form-label">郵便番号</span><br />
	        <%= form.text_field :postalcode %>
	      </div>

	      <div class="field">
		    <span class="form-label">住所</span><br />
	        <%= form.text_field :address %>
	      </div>
	      <!-- TODO: 文字数制限を記入する -->
	      <div class="field">
		    <span class="form-label">お店概要</span><br />
	        <%= form.text_area :description %>
	      </div>

	      <div class="field">
		    <span class="form-label">定休日</span><br />
	        <%= form.text_field :regular_holiday %>
	      </div>

	      <div class="field">
			<span class="form-label">アクセス</span><br />
	        <%= form.text_field :access %>
	      </div>

	      <div class="field">
		    <span class="form-label">営業時間</span><br />
	        <%= form.text_field :business_hours %>
	      </div>

	      <div class="field">
			<span class="form-label">開店年月日</span><br />
	        <%= form.text_field :opening_date %>
	      </div>

	      <div class="field">
		    <span class="form-label">HP</span><br />
	        <%= form.text_field :homepage %>
	      </div>

	      <%= form.fields_for :genres do |genre| %>

		    <div class="field">
			  <span class="form-label">ジャンル</span><br />
		        <%= genre.select :genre, Genre.genres.keys.map {|k| [I18n.t("enums.genre.genre.#{k}"), k]} %>
		    </div><br />
		  <% end %>

		<%= form.submit "お店編集", class: "shopedit-btn submit" %>

		<% end %>

	  </div>
	</div>
  </div>
</div>

app/views/shops/index.html.erb
<ul class="nav nav-pills genre-all" id="pills-tab" role="tablist">

  <li class="nav-item">
    <a class="nav-link genre-link active" id="pills-all-tab" data-toggle="pill" href="#pills-all" role="tab" aria-controls="pills-all" aria-selected="true">すべて</a>
  </li>

  <li class="nav-item">
    <a class="nav-link genre-link" id="pills-food_drink-tab" data-toggle="pill" href="#pills-food_drink" role="tab" aria-controls="pills-food_drink" aria-selected="false">食品・飲料</a>
  </li>

  <li class="nav-item">
    <a class="nav-link genre-link" id="pills-fashion-tab" data-toggle="pill" href="#pills-fashion" role="tab" aria-controls="pills-fashion" aria-selected="false">ファッション</a>
  </li>

  <li class="nav-item">
    <a class="nav-link genre-link" id="pills-dairy-tab" data-toggle="pill" href="#pills-dairy" role="tab" aria-controls="pills-dairy" aria-selected="false">日用品</a>
  </li>

  <li class="nav-item">
    <a class="nav-link genre-link" id="pills-general-tab" data-toggle="pill" href="#pills-general" role="tab" aria-controls="pills-general" aria-selected="false">雑貨</a>
  </li>

  <li class="nav-item">
    <a class="nav-link genre-link" id="pills-local-tab" data-toggle="pill" href="#pills-local" role="tab" aria-controls="pills-local" aria-selected="false">地産地消</a>
  </li>

  <li class="nav-item">
    <a class="nav-link genre-link" id="pills-select-tab" data-toggle="pill" href="#pills-select" role="tab" aria-controls="pills-select" aria-selected="false">セレクトショップ</a>
  </li>

</ul>

<div class="tab-content" id="pills-tabContent">

  <!-- お店全部を取り出す -->
  <div class="tab-pane fade show active" id="pills-all" role="tabpanel" aria-labelledby="pills-all-tab">
    <div class="container">
      <div class="row">
        <% @shops.each do |shop| %>
          <div class="col-md-4 index-col">
            <div class="card index-card" style="width: 22rem;">
              <%= link_to shop_path(shop.id) do %>
                <% if shop.shop_image.attached? %>
                  <%= image_tag shop.shop_image, :class => "index_shop_image" %>
                <% else %>
                  <%= image_tag "shop_no_image.jpg", :class => "index_shop_image" %>
                <% end %>
              <% end %>
              <div class="card-body index-card-body">
                <h5 class="card-text index-card-text">
                  <%= shop.shop_name %>
                </h5>
                <h6 class="card-text genre-text">
                  <% shop.genres.each do |f| %>
                    <%= f.genre_i18n %>
                  <% end %>
                  <i class="far fa-comment index-comment-count"><%= shop.comments.count %></i>
                </h6>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <%= paginate @shops, class: "paginate" %>
  </div>

  <!-- genreが0(食品・飲料)にあてはまるもの -->
  <div class="tab-pane fade" id="pills-food_drink" role="tabpanel" aria-labelledby="pills-food_drink-tab">
    <div class="container">
      <div class="row">
        <% @genre_food.each do |f| %>
          <div class="col-md-4 index-col">
            <div class="card index-card" style="width: 22rem;">
              <%= link_to shop_path(f.shop.id) do %>
                <% if f.shop.shop_image.attached? %>
                  <%= image_tag f.shop.shop_image, :class => "index_shop_image" %>
                <% else %>
                  <%= image_tag "shop_no_image.jpg", :class => "index_shop_image" %>
                <% end %>
              <% end %>
              <div class="card-body index-card-body">
                <h5 class="card-text index-card-text">
                  <%= f.shop.shop_name %>
                </h5>
                <h6 class="card-text genre-text">
                  <%= f.genre_i18n %>
                  <i class="far fa-comment index-comment-count"><%= f.shop.comments.count %></i>
                </h6>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <%= paginate @genre_food, class: "paginate" %>
  </div>

  <!-- genreが1(ファッション)にあてはまるもの -->
  <div class="tab-pane fade" id="pills-fashion" role="tabpanel" aria-labelledby="pills-fashion-tab">
    <div class="container">
      <div class="row">
        <% @genre_fashion.each do |f| %>
          <div class="col-md-4 index-col">
            <div class="card index-card" style="width: 22rem;">
              <%= link_to shop_path(f.shop.id) do %>
                <% if f.shop.shop_image.attached? %>
                  <%= image_tag f.shop.shop_image, :class => "index_shop_image" %>
                <% else %>
                  <%= image_tag "shop_no_image.jpg", :class => "index_shop_image" %>
                <% end %>
              <% end %>
              <div class="card-body index-card-body">
                <h5 class="card-text index-card-text">
                  <%= f.shop.shop_name %>
                </h5>
                <h6 class="card-text genre-text">
                  <%= f.genre_i18n %>
                  <i class="far fa-comment index-comment-count"><%= f.shop.comments.count %></i>
                </h6>
              </div>
             </div>
          </div>
        <% end %>
      </div>
    </div>
    <%= paginate @genre_fashion, class: "paginate" %>
  </div>

  <!-- genreが2(日用品)にあてはまるもの -->
  <div class="tab-pane fade" id="pills-dairy" role="tabpanel" aria-labelledby="pills-dairy-tab">
    <div class="container">
      <div class="row">
        <% @genre_daily.each do |f| %>
          <div class="col-md-4 index-col">
            <div class="card index-card" style="width: 22rem;">
              <%= link_to shop_path(f.shop.id) do %>
                <% if f.shop.shop_image.attached? %>
                  <%= image_tag f.shop.shop_image, :class => "index_shop_image" %>
                <% else %>
                  <%= image_tag "shop_no_image.jpg", :class => "index_shop_image" %>
                <% end %>
              <% end %>
              <div class="card-body index-card-body">
                <h5 class="card-text index-card-text">
                  <%= f.shop.shop_name %>
                </h5>
                <h6 class="card-text genre-text">
                  <%= f.genre_i18n %>
                  <i class="far fa-comment index-comment-count"><%= f.shop.comments.count %></i>
                </h6>
              </div>
             </div>
          </div>
        <% end %>
      </div>
    </div>
    <%= paginate @genre_daily, class: "paginate" %>
  </div>

  <!-- genreが3(雑貨)にあてはまるもの -->
  <div class="tab-pane fade" id="pills-general" role="tabpanel" aria-labelledby="pills-genaral-tab">
    <div class="container">
      <div class="row">
        <% @genre_general.each do |f| %>
          <div class="col-md-4 index-col">
            <div class="card index-card" style="width: 22rem;">
              <%= link_to shop_path(f.shop.id) do %>
                <% if f.shop.shop_image.attached? %>
                  <%= image_tag f.shop.shop_image, :class => "index_shop_image" %>
                <% else %>
                  <%= image_tag "shop_no_image.jpg", :class => "index_shop_image" %>
                <% end %>
              <% end %>
              <div class="card-body index-card-body">
                <h5 class="card-text index-card-text">
                  <%= f.shop.shop_name %>
                </h5>
                <h6 class="card-text genre-text">
                  <%= f.genre_i18n %>
                  <i class="far fa-comment index-comment-count"><%= f.shop.comments.count %></i>
                </h6>
              </div>
             </div>
          </div>
        <% end %>
      </div>
    </div>
    <%= paginate @genre_general, class: "paginate" %>
  </div>

  <!-- genreが4(地産地消)にあてはまるもの -->
  <div class="tab-pane fade" id="pills-local" role="tabpanel" aria-labelledby="pills-local-tab">
    <div class="container">
      <div class="row">
        <% @genre_local.each do |f| %>
          <div class="col-md-4 index-col">
            <div class="card index-card" style="width: 22rem;">
              <%= link_to shop_path(f.shop.id) do %>
                <% if f.shop.shop_image.attached? %>
                  <%= image_tag f.shop.shop_image, :class => "index_shop_image" %>
                <% else %>
                  <%= image_tag "shop_no_image.jpg", :class => "index_shop_image" %>
                <% end %>
              <% end %>
              <div class="card-body index-card-body">
                <h5 class="card-text index-card-text">
                  <%= f.shop.shop_name %>
                </h5>
                <h6 class="card-text genre-text">
                  <%= f.genre_i18n %>
                  <i class="far fa-comment index-comment-count"><%= f.shop.comments.count %></i>
                </h6>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <%= paginate @genre_local, class: "paginate" %>
  </div>

  <!-- genreが5(セレクトショップ)にあてはまるもの -->
  <div class="tab-pane fade" id="pills-select" role="tabpanel" aria-labelledby="pills-select-tab">
    <div class="container">
      <div class="row">
        <% @genre_select.each do |f| %>
          <div class="col-md-4 index-col">
            <div class="card index-card" style="width: 22rem;">
              <%= link_to shop_path(f.shop.id) do %>
                <% if f.shop.shop_image.attached? %>
                  <%= image_tag f.shop.shop_image, :class => "index_shop_image" %>
                <% else %>
                  <%= image_tag "shop_no_image.jpg", :class => "index_shop_image" %>
                <% end %>
              <% end %>
              <div class="card-body index-card-body">
                <h5 class="card-text index-card-text">
                  <%= f.shop.shop_name %>
                </h5>
                <h6 class="card-text genre-text">
                  <%= f.genre_i18n %>
                  <i class="far fa-comment index-comment-count"><%= f.shop.comments.count %></i>
                </h6>
              </div>
             </div>
          </div>
        <% end %>
      </div>
    </div>
    <%= paginate @genre_select, class: "paginate" %>
  </div>

</div>

app/views/shops/new.html.erb
<div class="container">
  <div class="row">
	<div class="card shopnew-card" style="width: 25rem;">
	  <div class="card-body">
		<h5 class="card-title">Shop投稿</h5>
		<hr class="my-3">
		  <%= form_with model: @shop do |form| %>

			<div class="field">
			  <span class="form-label">店舗画像:</span><br />
	          <%= form.file_field :shop_image %>
	         </div>

	        <div class="field">
			  <span class="form-label">店名</span><br />
	          <%= form.text_field :shop_name %>
	        </div>

	        <div class="field">
			  <span class="form-label">電話番号</span><br />
	          <%= form.text_field :phonenum %>
	        </div>

	        <div class="field">
		      <span class="form-label">郵便番号</span><br />
	          <%= form.text_field :postalcode %>
	        </div>

	        <div class="field">
			  <span class="form-label">住所</span><br />
	          <%= form.text_field :address %>
	        </div>
	        <!-- TODO: 文字数制限を記入する -->
	        <div class="field">
			  <span class="form-label">お店概要</span><br />
	          <%= form.text_area :description %>
	        </div>

	        <div class="field">
			  <span class="form-label">定休日</span><br />
	          <%= form.text_field :regular_holiday %>
	        </div>

	        <div class="field">
			  <span class="form-label">アクセス</span><br />
	          <%= form.text_field :access %>
	        </div>

	        <div class="field">
			  <span class="form-label">営業時間</span><br />
	          <%= form.text_field :business_hours %>
	        </div>

	        <div class="field">
			  <span class="form-label">開店年月日</span><br />
	          <%= form.text_field :opening_date %>
	        </div>

	        <div class="field">
			  <span class="form-label">HP</span><br />
	          <%= form.text_field :homepage %>
	        </div>

	        <%= form.fields_for :genres do |genre| %>

		      <div class="field">
			    <span class="form-label">ジャンル</span><br />
		          <%= genre.select :genre, Genre.genres.keys.map {|k| [I18n.t("enums.genre.genre.#{k}"), k]} %>
		      </div><br />
		    <% end %>

		    <%= form.submit "お店投稿", class: "submit" %>
		<% end %>

      </div>
	</div>
  </div>
</div>

app/views/shops/show.html.erb
<div class="content">
  <div class="container-fluid">
	<!-- お店の画像と店名・ジャンル・説明 -->
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <% if @shop.shop_image.attached? %>
  		  <%= image_tag @shop.shop_image, :class => "show_shop_image" %>
  		<% else %>
          <%= image_tag "shop_no_image.jpg", :class => "shop_shop_image" %>
        <% end %>
      </div>
      <div class="col-md-3"></div>
    </div>

    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
        <h2 class="card-title text-left"><%= @shop.shop_name %></h2>
        <p><%= simple_format(@shop.description) %></p>
      </div>
      <div class="col-md-3"></div>
    </div>

    <!-- お店の基本情報 -->
    <div class="row">
      <div class="col-md-3"></div>
      <div class="col-md-6">
	    <table>
		  <tr>
			<th>ジャンル</th>
			<td>
			  <% @shop.genres.each do |genre| %>
			    <%= genre.genre_i18n %>
		      <% end %>
			</td>
		  </tr>
		  <tr>
			<th>住所</th><td>〒<%= @shop.postalcode %><br><%= @shop.address %></td>
		  </tr>
		  <tr>
			<th>電話番号</th><td><%= @shop.phonenum %></td>
		  </tr>
		  <tr>
			<th>アクセス方法</th><td><%= @shop.access %></td>
		  </tr>
		  <tr>
			<th>営業時間</th><td><%= @shop.business_hours %></td>
		  </tr>
		  <tr>
		    <th>定休日</th><td><%= @shop.regular_holiday %></td>
		  </tr>
		  <tr>
		    <th>創業日</th><td><%= @shop.opening_date %></td>
		  </tr>
		  <tr>
			<th>HP</th><td><a href="<%= @shop.homepage %>"><%= @shop.homepage %></a></td>
		  </tr>
		</table>
		<p class="show-caution">※情報は変更になる場合があります。おでかけ前に必ず現地・施設へご確認ください。</p>
	  </div>
	  <div class="col-md-3"></div>
	</div>

	<!-- ボタンを配置 -->
	<div class="row">
	  <div class="col-md-4"></div>
	  <div class="col-md-4">
		<div class="btns">
		  <div class="btns-btn">
			<a href="http://www.facebook.com/share.php?u=https://ethinavi.herokuapp.com/shops/<%= @shop.id %>&t=<%= @shop.shop_name %>" target="_blank" rel="nofollow" class="btn-facebook mb-4 mt-2"><i class="fab fa-facebook-f"></i> 投稿する
			</a>
		  </div>
		  <div class="btns-btn">
			<a href="https://twitter.com/intent/tweet?text=<%= @shop.shop_name %>%20%23ethinavi%20%0a&url=https://ethinavi.herokuapp.com/shops/<%= @shop.id %>" target="_blank" rel="nofollow" class="btn-twitter mb-4 mt-2"><i class="fab fa-twitter"></i> 投稿する
			</a>
		  </div>
		  <!-- 管理者のみ表示 -->
			<% if user_signed_in? %>
			  <% if current_user.user_flag == 1 %>
				<div class="btns-btn">
				  <%= link_to edit_shop_path, class: "btn-edit mb-4 mt-2" do %>
					<i class="far fa-edit"> 編集する</i>
				  <% end %>
				</div>
				<div class="btns-btn">
				  <%= link_to shop_path , method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-destroy mb-4 mt-2" do %>
					<i class="far fa-trash-alt"> 削除する</i>
				  <% end %>
				</div>
			  <% end %>
			<% end %>

		</div>
	  </div>
		<div class="col-md-4"></div>
	</div>

		<hr color="#FCFCFC" width="100%" size="1">

	<div class="row">
	  <div class="col-md-3"></div>
	  <div class="col-md-6">
		<h6>コメント<%= @shop.comments.count %>件</h6><br>
		<% @shop.comments.each do |comment| %>
		  <div class="comment">
			<div class="comment-icon">

				<% if comment.user.user_image.attached? %>
                  <%= image_tag comment.user.user_image, :class => "image-comment" %>
                <% else %>
                  <%= image_tag "user_default.jpg", :class => "image-comment" %>
                <% end %>

			  <!-- < attachment_image_tag comment.user, :userimage, format: 'jpeg', fallback: "user_default.jpg", class: "image-comment" %> -->
			</div>
		    <div class="comment-name">
			  <%= comment.user.name %>
			</div>
		    <div class="comment-info">
			  <%= comment.created_at.strftime('%Y/%m/%d %H:%M') %>
			  <% if user_signed_in? && comment.user == current_user %>
	      	    <%= link_to '削除', shop_comment_path(@shop, comment), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "comment-delete" %>
	 		  <% end %>
		    </div>
			<div class="comment-message">
			  <%= simple_format(comment.comment) %>
		    </div>
		  </div>
		<% end %>

		<hr color="#FCFCFC" width="100%" size="1">

		<% if user_signed_in? %>
	      <div class="comment-form">

	      	<% if current_user.user_image.attached? %>
              <%= image_tag current_user.user_image, :class => "comment-form-image" %>
            <% else %>
              <%= image_tag "user_default.jpg", :class => "comment-form-image" %>
            <% end %>
			<!-- < attachment_image_tag current_user, :userimage, format: 'jpeg', fallback: "user_default.jpg", class: "comment-form-image" %> -->

			<%= form_for([@shop, @comment]) do |f| %>
			  <%= f.text_area :comment, id: "text", class: "comment-text-area", placeholder: " コメントを入力" %>
			  <%= f.submit "送信", id: "submit", class: "comment-submit" %>
			<% end %>
		  </div>
		<% else %>
		  <div class="comment-if">
			コメントを投稿するには、<%= link_to "ログイン", new_user_session_path, class: "comment-if-link" %>
			または <%= link_to "新規登録", new_user_registration_path, class: "comment-if-link" %> する必要があります
		  </div>
		<% end %>
	  </div>
	  <div class="col-md-3"></div>
	</div>

  </div>
</div>