config/routes.rb
Rails.application.routes.draw do

  root "shops#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:edit,:update]
  resources :shops do
    resources :comments
  end
  delete "/shops/:id" => "shops#destroy", as: "destroy_shop"
  get "home/about" => "home#about"
  get "home/top" => "home#top"
  get "home/terms" => "home#terms"
  get "home/privacy" => "home#privacy"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  	def about
    end

    def top
    end

    def terms
    end

    def privacy
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="container">
  <div class="row">
    <div class="card border border-0" style="width: 72rem;">
      <div class="card-body">
        <h1 class="about-title"><span data-ruby="エシナビ">Ethinavi</span></h1>
		  <p class="about-text">
		    エシカル消費を通じて社会問題の解決に貢献したいユーザが<br>
		    私達の身近にあるエシカル消費を実行できるお店を探し、応援できるサイトです。
		  </p>
		  <img src="/assets/home-about.jpg" alt="サイトの画面一覧" class="about-img">

		    <% if user_signed_in? %>
			  <div class="about-btns">
			    <div class="btns">
				  <div class="btns-btn">
					<%= link_to "エシカルな消費？", home_top_path, { :class => "btn-top" } %>
				  </div>
				</div>
			  </div>
			<% else %>
			  <div class="about-btns">
				<div class="btns">
				  <div class="btns-btn">
					<%= link_to "ログイン", new_user_session_path, { :class => "btn-login" } %>
				  </div>
					<div class="btns-btn">
					  <%= link_to "エシカルな消費？", home_top_path, { :class => "btn-top" } %>
					</div>
					<div class="btns-btn">
					  <%= link_to "新規登録", new_user_registration_path, { :class => "btn-signup" } %>
					</div>
				</div>
			  </div>
			<% end %>

      </div>
	</div>
  </div>
</div>

app/views/home/privacy.html.erb
<div class="container p-t45">
  <div class="row">
  	<div class="col-md-2"></div>

  	<div class="col-md-8">
  	  <div class="m-b3">
  		  <h1 class="privacy-title">プライバシーポリシー</h1>
  	  </div>
  	  <div class="align-left small-text">
  	  	<p>
  	  	  ethinavi（以下、「本サービス」）では、本サービスをご利用されるユーザーの個人情報の取扱について以下のとおり定め、個人情報の保護に努めてまいります。
  	  	</p>

  	  	<h3 class="m-t4 subtitle">1.個人情報の利用目的</h3>
  	  	<p>
  	      運営者は、以下の利用目的のためにユーザーの個人情報を収集します。
  	  	</p>
  	  	<ol>
  	  	  <li>本サービスを提供するため</li>
  	  	  <li>ログイン時における本人認証、その他本サービスの運営に必要な管理のため</li>
  	  	  <li>本サービスの利用規約に違反する行為への対応及び当該違反行為の防止のため</li>
  	  	  <li>本サービスに関する規約、ポリシー等の変更等をお客様に通知するため</li>
  	  	  <li>紛争、訴訟などへの対応のため</li>
  	  	  <li>本サービスに関するご案内、お客様からのお問い合わせ等への対応のため</li>
  	  	</ol>

  	  	<h3 class="m-t4 subtitle">2.個人情報の第三者提供について</h3>
  	  	<p>
  	  	  法令に定める場合を除き、個人情報を事前に本人の同意を得ることなく第三者に提供することは行いません。
  	    </p>

  	  	<h3 class="m-t4 subtitle">3.個人情報の管理について</h3>
  	  	<p>
  	      収集された個人情報は適切な管理の下で安全に蓄積・保管し、不正アクセス、紛失、破壊、改竄、漏洩などの危険に対して適切に技術的、組織的な予防および対策を講じます。 個人情報もしくは情報システムを取り扱う業務を外部に委託する場合には、委託先の厳正な管理監督の下で行います。
  	  	</p>

  	  	<h3 class="m-t4 subtitle">4.個人情報の開示・訂正・利用停止・消去・苦情について</h3>
  	  	<p>
  	  	  当社は、本人が自己の個人情報について、開示・訂正・利用停止・消去などを求める権利を有していることを確認し、「個人情報取扱に関するお問い合わせ窓口」を設け、これらの要求や苦情に対して速やかに対処します。
  	  	</p>

  	  	<h3 class="m-t4 subtitle">5.個人情報に関するお問い合わせ、開示等の請求に関する窓口</h3>
  	  	<p><a href="https://twitter.com/ethinavi">ethinavi公式Twitter</a>へご連絡ください。</p>

  	  </div>
  	</div>
  	<div class="col-md-2"></div>
  </div>
</div>

app/views/home/terms.html.erb
<div class="container p-t45">
  <div class="row">
  	<div class="col-md-2"></div>

  	<div class="col-md-8">
  	  <div class="m-b3">
  		<h1 class="terms-title">利用規約</h1>
  	  </div>
  	  <div class="align-left small-text">
  	  	<p>
  	  	  この利用規約（以下、「本規約」といいます。）は、ethinavi（以下、本サービス」といいます。）の利用条件を定めるものです。 ユーザーの皆さま（以下、「ユーザー」といいます。）には、本規約に従って、本サービスをご利用いただきます。
  	  	</p>

  	  	<h3 class="m-t4 subtitle">1.規約の適用</h3>
  	  	<p>
  	      本規約は、ユーザーと本サービスの利用に関わる一切の関係に適用されるものとします。
  	  	</p>

  	  	<h3 class="m-t4 subtitle">2.規約の変更</h3>
  	  	<ol>
  	  	  <li>はユーザーの了解を得ることなく本規約を変更することがあります。この場合、本サービスの利用条件は、変更後の本規約によるものとします。</li>
  	  	  <li>変更後の規約は、運営者が別途定める場合を除き、本サイト上に表示した時点より、効力を生じるものとします。</li>
  	  	</ol>

  	  	<h3 class="m-t4 subtitle">3.利用者登録</h3>
  	  	<p>
  	      新規登録により、新規登録が完了した時点で利用者となり、本規約の条件による本サービスの利用の許可が運営者より利用者に有効に付与されるものとします。
  	  	</p>

  	  	<h3 class="m-t4 subtitle">4.禁止行為</h3>
  	  	<p>
  	  	  運営者は、ユーザーが次の各号のいずれかに該当すると判断した場合、ユーザーへの事前の通知若しくは催告を要することなく、利用禁止処分または本利用規約の全部若しくは一部を解約することができるものとします。
  	  	</p>
  	  	<ol>
  	  	  <li>本サービスの運営を妨害する行為。</li>
  	  	  <li>虚偽の情報を登録・記入・送信する行為。</li>
  	  	  <li>過去に本利用規約違反等の理由によりユーザー資格の取り消しを受けていたにも関わらず、ユーザー登録の申込をする行為。</li>
  	  	  <li>コンピュータ・ウィルス等の有害なコンピュータプログラム等を送信または頒布する行為、チェーンメール・スパムメール等の送信を目的とする行為、並びに本サービスに著しく負荷のかかる行為。</li>
  	      <li>本サービスにより利用しうる情報を改ざんまたは消去する行為</li>
  	  	  <li>運営者または第三者の財産、プライバシー、名誉または肖像権を侵害する行為、または侵害するおそれのある行為、ストーカー的行為。</li>
  	  	  <li>運営者または第三者を差別・誹謗中傷し、その名誉または信用を毀損する行為、並びに人種的・民族的・宗教的に不快感を与える行為。</li>
  	  	  <li>わいせつな映像・画像等の配信またはそれらを掲載する他のウェブサイトへの誘導をする行為。</li>
  	  	  <li>その他、公序良俗に違反し、または他者の権利を侵害すると運営者が判断した行為。</li>
  	  	  <li>その他運営者が不適切であると判断する行為。</li>
  	  	</ol>

  	  	<h3 class="m-t4 subtitle">5.サービスの一時的な中断</h3>
  	  	<p>運営者は、次の各号いずれかの事由に該当する場合、ユーザーに事前に通知することなく、一時的に本サービスの運営を中断することがあります。</p>
  	  	<ol>
  	      <li>本サービスまたは関連設備の保守を定期的または緊急に行うとき。</li>
  	  	  <li>本サービスで利用する通信回線、電力等の提供が中断されたとき。</li>
  	  	  <li>火災、停電、地震、台風、洪水、津波等の天災や疫病の発生等、運営者が支配できない事情（運営者が利用しているサーバーで生じた事情を含みます。）により本サービスの運営ができないとき。</li>
  	  	  <li>その他運営者が必要と判断したとき。</li>
  	  	  <li>運営者は、理由を問わず、本サービスの運営の遅滞、中断または停止に起因して、ユーザー、顧客または第三者が被った損害について、一切責任を負わないものとします。</li>
  	  	</ol>

  	  	<h3 class="m-t4 subtitle">6.免責事項</h3>
  	  	<p>本サービスは、ユーザーに事前に通知することなく、一時的に本サービスの運営を中断することがあります。</p>
  	  	<ol>
  	      <li>本サービスの利用において、ユーザーの責により運営者その他の第三者に損害が発生した場合または権利が侵害された場合においてこれを解決するものとし、本サービス及び当該第三者に損害を賠償することとします。</li>
  	      <li>天災地変、戦争・暴動・内乱、法令の制定・改廃、公権力による命令・処分、ストライキ等の争議行為、輸送機関の事故、その他当事者の責に帰し得ない事由による本利用規約に基づく債務の履行の遅滞または不能が生じた場合は、当該当事者はその責を負わないものとします。</li>
  	  	  <li>運営者は、ユーザーに対し、以下の各号に該当する損害、ならびに以下の各号に付随する２次的なデータの漏洩、損失、損害にかかる損害について責任を負わないものとします。</li>
  	  	  <li>運営者が提供していないプログラムによって生じる損害。</li>
  	  	  <li>運営者以外の第三者による不正な行為によって生じる損害。</li>
  	      <li>ハッカー及びクラッカーによるサーバーへの侵入または攻撃等の行為による損害。</li>
  	  	  <li>運営者が本サービスのために用いるサーバーにおいて生じた事情により生じる損害。</li>
  	  	  <li>本サービスのバグによって生じる損害。</li>
  	  	  <li>運営者は、本サービスについて、その完全性、特定目的適合性、その他一切保証しないものとします。運営者は、本サービスや本サイトの提供が中断することなく継続することを保証しません。本サービスは、本サービスや本サイトの提供が停止または中止した場合も、ユーザーや第三者に生じた損害について責任を負いません。</li>
  	  	  <li>運営者は、本サービスにユーザーがアップロードするデータ・情報に関しては、一切責任を負わないものとします。本サービスにアップロードするデータ・情報の正確性や当該情報をアップデートする責任は、全てユーザーにあります。</li>
  	  	  <li>運営者は、本サイトでの広告の表示・掲載を、第三者について行う場合があります。ユーザーが、本サイトでの広告を通じて第三者から商品・サービスを購入する等、第三者と何らかの契約をされる場合、当該契約の当事者はユーザーと第三者であり、本サービスはいかなる責任も負いません。</li>
  	  	  <li>ユーザーは、本サービスにおいて保存するデータについて、自らバックアップを行う義務を負います。運営者は、本サービスにおいて、運営者の管理下にあるインターネットサーバーに保管・蓄積されるユーザーのデータについてバックアップを行いますが、本サービスによるバックアップにも関わらず、本サービスに保管・蓄積されたユーザーのデータが消失、毀損した場合には、本サービスは、ユーザーや第三者に対していかなる責任も負いません。</li>
		</ol>

		<h3 class="m-t4 subtitle">7.本サービスの終了</h3>
		<p>運営者は、次の各号いずれかの事由に該当する場合、ユーザーに事前に通知することなく、一時的に本サービスの運営を中断することがあります。</p>
		<ol>
	      <li>運営者は、相当の周知期間をもってユーザーに通知の上、利用者に対する本サービス及び本サービスの一部を終了することができるものとします。</li>
		  <li>前項の通知は、本サイト上での掲示及び利用者への電子メールやWebサイト上への掲載によるものとします。</li>
		  <li>運営者はユーザーに対する通知後、本サービスを終了した場合には、利用者に対して本サービスは終了に伴い生じる損害、損失、その他の費用の賠償または補償を免れるものとします。</li>
		</ol>

		<h3 class="m-t4 subtitle">8.合意管轄等</h3>
		<p>本規約の解釈にあたっては、日本法を準拠法とします。本サービスに関して紛争が生じた場合には、 本サービスの本店所在地を管轄する裁判所を専属的合意管轄とします。</p>

		<h3 class="m-t4 subtitle">9.附則</h3>
		<p>2019年6月23日 制定・施行</p>

  	  </div>
  	</div>
  	<div class="col-md-2"></div>
  </div>
</div>

app/views/home/top.html.erb
<div class="container">
  <div class="row">
    <div class="card border border-0" style="width: 72rem;">
      <div class="card-body">
		<h1 class="top-title">世界を救うエシカル消費</h1>

		<div class="img">
		  <img src="/assets/top1.jpg" alt="サイトの画面一覧" class="top-img">
		  <img src="/assets/top2.jpg" alt="サイトの画面一覧" class="top-img">
		  <img src="/assets/top3.jpg" alt="サイトの画面一覧" class="top-img">
		</div>

		<p class="top-text">
		  ヒトは生きていく上で消費から逃れることはできません。<br>衣・食・住と生活に不可欠な3要素だけでも、そこで消費する洋服や食料、エネルギーは決して少なくありません。<br>これらは「いつ、どこで、誰が、どうやって作ったのか...。」それは意図的に調べない限り、知らないまま日々が過ぎていきます。
		</p>

		<p class="top-text">
		  貧困や人権問題、気候変動といった問題が世界中で「喫緊の課題」です。<br>
		  これらの問題は主として、先進国による大量生産、大量消費に端を発する問題なのです。<br>先進国に暮らす人々の欲望を満たすために、劣悪な環境で長時間働く従業員や、教育を受けられず強制的に働かせられてる子供達がいたり、<br>地球の再生能力よりもはるかに早く資源を使い、環境が破壊されたりしているのが現実です。
		</p>

		<p class="top-text">
		  <b>エシカル消費</b>とはそういったことのないような商品を購入し、消費すること。<br>
		  仮に、消費者が一気に<b>エシカル消費</b>を実行するとします。そうなったときに社会や経済に与える影響は、とても大きいものになります。<br>
		  一人ひとりの消費者が自分たちの力の大きさを認識し、<br>
		  「お金を払うことを通じて、社会問題の解決に貢献しよう！」と考えて消費すれば、<br>
		  私たちの日常が「<b>エシカル</b>そのもの」になっていきます。
		</p>

		<% if user_signed_in? %>
		  <div class="top-btns">
			<div class="btns">
			  <div class="btns-btn">
				<%= link_to "Ethinaviって？", home_about_path, { :class => "btn-about" } %>
			  </div>
			</div>
		  </div>
		<% else %>
		  <div class="top-btns">
		    <div class="btns">
			  <div class="btns-btn">
				<%= link_to "ログイン", new_user_session_path, { :class => "btn-login" } %>
			  </div>
			  <div class="btns-btn">
				<%= link_to "Ethinaviって？", home_about_path, { :class => "btn-about" } %>
			  </div>
			  <div class="btns-btn">
				<%= link_to "新規登録", new_user_registration_path, { :class => "btn-signup" } %>
			  </div>
			</div>
		  </div>
		<% end %>

      </div>
	</div>
  </div>
</div>