config/routes.rb
Rails.application.routes.draw do

  root "shops#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:edit,:update]
  resources :shops do
    resources :comments
  end
  delete "/shops/:id" => "shops#destroy", as: "destroy_shop"
  get "home/about" => "home#about"
  get "home/top" => "home#top"
  get "home/terms" => "home#terms"
  get "home/privacy" => "home#privacy"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/ fb# website: http://ogp.me/ns/ website#">
    <meta property="og:title" content="Ethinavi" />
    <meta property="og:description" content="世界を救う、エシカル消費。エシカルな消費が実践できるお店を発見・応援できるサービスです。" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://ethinavi.herokuapp.com" />
    <meta property="og:site_name" content="Ethinavi" />
    <meta property="og:image" content="https://ethinavi.herokuapp.com/assets/ethinavi.jpg" />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@ethinavi" />
    <title>Ethinavi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="shortcut icon" href="/assets/favicon.ico" type="image/x-icon" />
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Noto+Sans+JP:400,700" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
  </head>

  <body>
    <div class="wrapper">
      <header>
        <% if user_signed_in? %>
          <!-- ログイン済みユーザ -->

          <% if current_user.user_flag == 0 %>

            <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FFFFFF;">

              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="ナビゲーションの切替">
                <span class="navbar-toggler-icon"></span>
              </button>

              <a class="navbar-brand logo" href="/">Ethinavi</a>

              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav mr-auto"></ul>
                <ul class="navbar-nav">
                  <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" id="navbarDropdownMenuLink" aria-haspopup="true" aria-expanded="false">
                      <% if current_user.user_image.attached? %>
                        <%= image_tag current_user.user_image, :class => "header-image" %>
                      <% else %>
                        <%= image_tag "user_default.jpg", :class => "header-image" %>
                      <% end %>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                      <%= link_to "編集", edit_user_path(current_user.id), class: "dropdown-item" %>
                      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                    </div>
                  </li>
                  <li class="nav-item header-blanck"></li>
                </ul>
              </div>

            </nav>
          <!-- 管理人 -->
          <% elsif current_user.user_flag == 1 %>

            <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FFFFFF;">

              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="ナビゲーションの切替">
                <span class="navbar-toggler-icon"></span>
              </button>

              <a class="navbar-brand logo" href="/">Ethinavi</a>

              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav mr-auto"></ul>
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <%= link_to "新規投稿", new_shop_path, class: "btn-shopnew" %>
                  </li>
                  <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" id="navbarDropdownMenuLink" aria-haspopup="true" aria-expanded="false">
                      <% if current_user.user_image.attached? %>
                        <%= image_tag current_user.user_image, :class => "header-image" %>
                      <% else %>
                        <%= image_tag "user_default.jpg", :class => "header-image" %>
                      <% end %>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                      <%= link_to "編集", edit_user_path(current_user.id), class: "dropdown-item" %>
                      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                    </div>
                  </li>
                  <li class="nav-item header-blanck"></li>
                </ul>
              </div>

            </nav>

          <% end %>
          <!-- 新規登録してないユーザ -->
        <% else %>

            <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FFFFFF;">

              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="ナビゲーションの切替">
                <span class="navbar-toggler-icon"></span>
              </button>

              <a class="navbar-brand logo" href="/">Ethinavi</a>

              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav mr-auto"></ul>
                <ul class="navbar-nav">

                  <li class="nav-item">
                    <%= link_to "新規登録",  new_user_registration_path, class: "btn-header-signup" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログイン", new_user_session_path, class: "btn-header-login" %>
                  </li>
                  <li class="nav-item header-blanck"></li>
                </ul>
              </div>

            </nav>
        <% end %>
      </header>

      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>

      <%= yield %>

      <footer class="footer">
        <div class="footer-container">
          <div class="footer-nav">
            <div class="footer-links">
              <a href="/home/terms" class="footer-item">利用規約</a>
              /
              <a href="/home/privacy" class="footer-item">プライバシーポリシー</a>
              /
              <a href="/home/about" class="footer-item">ethinaviとは</a>
              /
              <a href="/home/top" class="footer-item">エシカル消費</a>
              /
              <a href="https://twitter.com/ethinavi" class="footer-item">お問い合わせ・改善の声</a>
            </div>
          </div>
          <p class="footer-text">©︎ 2019 Ethinavi All rights reseverd.</p>
        </div>
      </footer>
    </div>
  </body>
</html>